---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/fluxcd/flux2
  ref:
    tag: v0.35.0
  ignore: |
    # exclude all
    /*
    # include manifest dir
    !/manifests
