---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dolos
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/scuffe82/dolos-flux.git
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/kubernetes
